stages:
  download_dataset:
    cmd: python scripts/download_dataset.py
    deps:
      - scripts/download_dataset.py
    params:
      - dataset
    outs:
      - data/midi_dataset.zip
      - data/midi_dataset/
  midi_to_dataset:
    matrix:
      mode: [ 'note_events']
    cmd: python scripts/midi_to_dataset.py --mode ${item.mode}
    deps:
      - scripts/midi_to_dataset.py
      - data/midi_dataset/
    params:
      - dataset
      - preprocess.sample_rate
      - preprocess.note_count
    outs:
      - data/preprocessed_${item.mode}.pkl